//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point85.ShiftSharp.Schedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Point85.ShiftSharp.Schedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks.
        /// </summary>
        internal static string breaks {
            get {
                return ResourceManager.GetString("breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration must be 24 hours or less..
        /// </summary>
        internal static string duration_not_allowed {
            get {
                return ResourceManager.GetString("duration.not.allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration is not defined..
        /// </summary>
        internal static string duration_not_defined {
            get {
                return ResourceManager.GetString("duration.not.defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting time of {0} must be earlier than {1}..
        /// </summary>
        internal static string end_earlier_than_start {
            get {
                return ResourceManager.GetString("end.earlier.than.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is not defined..
        /// </summary>
        internal static string name_not_defined {
            get {
                return ResourceManager.GetString("name.not.defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-working period {0} has already been created..
        /// </summary>
        internal static string nonworking_period_already_exists {
            get {
                return ResourceManager.GetString("nonworking.period.already.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string period_end {
            get {
                return ResourceManager.GetString("period.end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string period_start {
            get {
                return ResourceManager.GetString("period.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation {0} has already been created..
        /// </summary>
        internal static string rotation_already_exists {
            get {
                return ResourceManager.GetString("rotation.already.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in rotation.
        /// </summary>
        internal static string rotation_days {
            get {
                return ResourceManager.GetString("rotation.days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation duration.
        /// </summary>
        internal static string rotation_duration {
            get {
                return ResourceManager.GetString("rotation.duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string rotation_off {
            get {
                return ResourceManager.GetString("rotation.off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string rotation_on {
            get {
                return ResourceManager.GetString("rotation.on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage worked.
        /// </summary>
        internal static string rotation_percentage {
            get {
                return ResourceManager.GetString("rotation.percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation periods.
        /// </summary>
        internal static string rotation_periods {
            get {
                return ResourceManager.GetString("rotation.periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation start.
        /// </summary>
        internal static string rotation_start {
            get {
                return ResourceManager.GetString("rotation.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled working time.
        /// </summary>
        internal static string rotation_working {
            get {
                return ResourceManager.GetString("rotation.working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total team coverage.
        /// </summary>
        internal static string schedule_coverage {
            get {
                return ResourceManager.GetString("schedule.coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-working periods.
        /// </summary>
        internal static string schedule_non {
            get {
                return ResourceManager.GetString("schedule.non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string schedule_shifts {
            get {
                return ResourceManager.GetString("schedule.shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string schedule_teams {
            get {
                return ResourceManager.GetString("schedule.teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total non-working time.
        /// </summary>
        internal static string schedule_total {
            get {
                return ResourceManager.GetString("schedule.total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled working time.
        /// </summary>
        internal static string schedule_working {
            get {
                return ResourceManager.GetString("schedule.working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift {0} has already been created..
        /// </summary>
        internal static string shift_already_exists {
            get {
                return ResourceManager.GetString("shift.already.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift {0} is being used in a work schedule..
        /// </summary>
        internal static string shift_in_use {
            get {
                return ResourceManager.GetString("shift.in.use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift {0} spans midnight and the working time between {1} and {2} is ambiguous..
        /// </summary>
        internal static string shift_spans_midnight {
            get {
                return ResourceManager.GetString("shift.spans.midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string shifts_day {
            get {
                return ResourceManager.GetString("shifts.day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No working shifts.
        /// </summary>
        internal static string shifts_non_working {
            get {
                return ResourceManager.GetString("shifts.non.working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working shifts.
        /// </summary>
        internal static string shifts_working {
            get {
                return ResourceManager.GetString("shifts.working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time is not defined..
        /// </summary>
        internal static string start_not_defined {
            get {
                return ResourceManager.GetString("start.not.defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} has already been created..
        /// </summary>
        internal static string team_already_exists {
            get {
                return ResourceManager.GetString("team.already.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average hours worked per week.
        /// </summary>
        internal static string team_hours {
            get {
                return ResourceManager.GetString("team.hours", resourceCulture);
            }
        }
    }
}
